version: "3.9"

services:
  postgres_db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rust_query_service:
    build: ./rust-service
    container_name: rust_query_service
    environment:
      - DATABASE_URL=postgres://user:password@postgres_db:5432/dbname
    depends_on:
      - postgres_db
    ports:
      - "8080:8080"

  kong_gateway:
    image: kong:3.7
    container_name: kong_gateway
    restart: always
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/etc/kong/kong.yml
      - KONG_PROXY_LISTEN=0.0.0.0:8000
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    volumes:
      - ./kong.yml:/etc/kong/kong.yml:ro
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - rust_query_service

volumes:
  postgres_data:
